### ISSUE TITLE
[Feature]: Set hard disk threshold values

### ISSUE THREAD

**Issue by Cynexxde** [NETWAYS/check_braintower#17]
Hello everyone,

we recently had the problem that the hard disk ran out of space, cause of logs. According to support, this is also a known problem, but no solution has been provided. There will probably be no update in the near future, so we will have to delete the logs manually on a regular basis. 

Is it possible to add a feature to monitor the free disk space so that performance data can be obtained and threshold values can be set?

**Comment by martialblog** [comment]
Hi, 

I checked the API documentation and that might actually be possible:

https://docs.brevis.one/current/de/Content/Functionality/Status%20Functions/Monitor%20the%20SMS%20Gateway.htm?tocpath=Funktionalit%C3%A4t%7CStatusfunktionen%7C_____5

The check.php should return a `disk` value. 

@Cynexxde could you provide an example output of the check.php API? That would help with development.

**Comment by Cynexxde** [comment]
I get the following string from the checkphp. -> `http://<IP address gateway>/check.php`

`que: 0 failed: 0 signal: -95 dBm total: 885 state: SIGNAL_WARNING load: 0.07;0.1;0.09 time: 1713865490 disk: 1400246272 uptime: 19:55, 0 users power:`

**Comment by martialblog** [comment]
Thanks. We will have a look at it, should be doable.

**Comment by Cynexxde** [comment]
Nice thanks ^^

**Comment by martialblog** [comment]
Started to implement this. 
I have some example code on this branch: https://github.com/NETWAYS/check_brevisone/tree/feature/add-disk-check

Since we don't know the limit of the disk, we cannot have defaults for the parameters. Each user will have to check their devices disk capacity and set an appropriate value

**Comment by Cynexxde** [comment]
Thank you for the implementation. At first sight, it works as it should.

**Comment by martialblog** [comment]
Thanks for testing. I will try to finish this soon

**Comment by martialblog** [comment]
Release is out now https://github.com/NETWAYS/check_brevisone/releases/tag/v4.0.0
